package org.rsmod.content.skills.agility.shortcuts

import org.rsmod.content.skills.agility.AgilityAnims
import org.rsmod.content.skills.agility.shortcuts.ShortcutMove.Balance
import org.rsmod.content.skills.agility.shortcuts.ShortcutMove.Climb
import org.rsmod.content.skills.agility.shortcuts.ShortcutMove.Hop
import org.rsmod.content.skills.agility.shortcuts.ShortcutMove.Jump
import org.rsmod.content.skills.agility.shortcuts.ShortcutMove.Squeeze
import org.rsmod.map.CoordGrid

/**
 * Agility shortcuts, in level order. Sides were read from the game map: each is the tile carrying
 * the shortcut's map icon or the first free tile past the loc on that side. Shortcuts gated behind
 * quests, diaries or grapples are left out until those systems exist.
 */
object AgilityShortcuts {
    private fun tile(x: Int, z: Int, level: Int = 0): CoordGrid = CoordGrid(x, z, level)

    private val crawl = Squeeze()
    private val tunnel = ShortcutMove.Tunnel()
    private val pipe = ShortcutMove.PIPE
    private val climbOver = Jump(AgilityAnims.WALL_CLIMB_OVER)

    val all: List<AgilityShortcut> =
        listOf(
            AgilityShortcut(
                name = "Crumbling wall",
                level = 5,
                xp = 0.5,
                locs = listOf("loc.fai_falador_castle_crumble_mid"),
                sideA = tile(2934, 3355),
                sideB = tile(2936, 3355),
                move = climbOver,
            ),
            AgilityShortcut(
                name = "Fence",
                level = 13,
                xp = 0.0,
                locs = listOf("loc.lumbridge_sc_fencejump"),
                sideA = tile(3240, 3335),
                sideB = tile(3240, 3334),
                move = Jump(),
            ),
            AgilityShortcut(
                name = "Underwall tunnel",
                level = 16,
                xp = 0.0,
                locs = listOf("loc.yanille_castlehole_sc", "loc.yanille_castlewall_sc"),
                sideA = tile(2575, 3112),
                sideB = tile(2575, 3107),
                move = tunnel,
            ),
            AgilityShortcut(
                name = "Crack",
                level = 17,
                xp = 0.0,
                locs = listOf("loc.zeah_cata_crack"),
                sideA = tile(1646, 10000),
                sideB = tile(1648, 10009),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Broken window",
                level = 18,
                xp = 3.0,
                locs = listOf("loc.slayertower_window_shortcut_through"),
                sideA = tile(3444, 3533),
                sideB = tile(3442, 3531),
                move = climbOver,
            ),
            AgilityShortcut(
                name = "Log balance",
                level = 20,
                xp = 8.5,
                locs = listOf("loc.mine_log_balance1"),
                sideA = tile(2598, 3477),
                sideB = tile(2603, 3477),
                move = Balance(listOf(tile(2599, 3477), tile(2600, 3477), tile(2601, 3477), tile(2602, 3477))),
            ),
            AgilityShortcut(
                name = "Underwall tunnel",
                level = 21,
                xp = 0.0,
                locs = listOf("loc.varrock_sc_tunnel_west", "loc.varrock_sc_tunnel_east"),
                sideA = tile(3137, 3517),
                sideB = tile(3142, 3512),
                move = tunnel,
            ),
            AgilityShortcut(
                name = "Underwall tunnel",
                level = 26,
                xp = 0.0,
                locs = listOf("loc.falador_sc_castlewall_south", "loc.falador_sc_castlewall_north"),
                sideA = tile(2948, 3309),
                sideB = tile(2948, 3313),
                move = tunnel,
            ),
            AgilityShortcut(
                name = "Rocks",
                level = 29,
                xp = 0.0,
                locs = listOf("loc.mount_karuulm_shortcut_rocks_low"),
                sideA = tile(1324, 3777),
                sideB = tile(1324, 3785),
                move = Climb(),
            ),
            AgilityShortcut(
                name = "Stepping stones",
                level = 30,
                xp = 3.0,
                locs = listOf("loc.zqrockjump1", "loc.zqrockjump3"),
                sideA = tile(2925, 2951),
                sideB = tile(2925, 2947),
                move = Hop(listOf(tile(2925, 2950), tile(2925, 2949), tile(2925, 2948))),
            ),
            AgilityShortcut(
                name = "Stepping stone",
                level = 31,
                xp = 3.0,
                locs = listOf("loc.lumbridge_sc_stepstone"),
                sideA = tile(3149, 3363),
                sideB = tile(3154, 3363),
                move = Hop(listOf(tile(3151, 3363))),
            ),
            AgilityShortcut(
                name = "Log balance",
                level = 33,
                xp = 4.0,
                locs = listOf("loc.ardougne_log_balance_left_sc", "loc.ardougne_log_balance_right_sc"),
                sideA = tile(2598, 3336),
                sideB = tile(2602, 3336),
                move = Balance(listOf(tile(2599, 3336), tile(2600, 3336), tile(2601, 3336))),
            ),
            AgilityShortcut(
                name = "Crack",
                level = 34,
                xp = 0.0,
                locs = listOf("loc.zeah_cata_crack"),
                sideA = tile(1706, 10078),
                sideB = tile(1716, 10056),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Rocks",
                level = 37,
                xp = 0.0,
                locs = listOf("loc.gnome_stronghold_sc_rock_top", "loc.gnome_stronghold_sc_rock_bottom"),
                sideA = tile(2486, 3515),
                sideB = tile(2489, 3521),
                move = Climb(),
            ),
            AgilityShortcut(
                name = "Rocks",
                level = 38,
                xp = 0.0,
                locs = listOf("loc.alkharid_mine_sc_top", "loc.alkharid_mine_sc_bottom"),
                sideA = tile(3306, 3315),
                sideB = tile(3302, 3315),
                move = Climb(),
            ),
            AgilityShortcut(
                name = "Narrow crevice",
                level = 42,
                xp = 0.0,
                locs = listOf("loc.dwarf_mines_sc_wall_crack"),
                sideA = tile(3028, 9806),
                sideB = tile(3035, 9806),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Underwall tunnel",
                level = 42,
                xp = 0.0,
                locs = listOf("loc.draynor_diary_under_wall_w", "loc.draynor_diary_under_wall_e"),
                sideA = tile(3066, 3257),
                sideB = tile(3070, 3257),
                move = tunnel,
            ),
            AgilityShortcut(
                name = "Log balance",
                level = 48,
                xp = 4.0,
                locs = listOf("loc.slayer_river_sc_logbalance_1", "loc.slayer_river_sc_logbalance_3"),
                sideA = tile(2722, 3596),
                sideB = tile(2722, 3592),
                move = Balance(listOf(tile(2722, 3595), tile(2722, 3594), tile(2722, 3593))),
            ),
            AgilityShortcut(
                name = "Obstacle pipe",
                level = 51,
                xp = 10.0,
                locs = listOf("loc.varrock_dungeon_pipe_sc"),
                sideA = tile(3149, 9906),
                sideB = tile(3155, 9906),
                move = pipe,
            ),
            AgilityShortcut(
                name = "Broken fence",
                level = 57,
                xp = 0.0,
                locs = listOf("loc.viking_pike_defence_broken"),
                sideA = tile(2688, 3697),
                sideB = tile(2691, 3697),
                move = Jump(),
            ),
            AgilityShortcut(
                name = "Tunnel",
                level = 60,
                xp = 0.0,
                locs =
                    listOf(
                        "loc.cavewall_shortcut_royal_titans_east",
                        "loc.cavewall_shortcut_royal_titans_west",
                    ),
                sideA = tile(2991, 9546),
                sideB = tile(2968, 9550),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Spikey chain",
                level = 61,
                xp = 0.0,
                locs = listOf("loc.slayertower_sc_chainbottom", "loc.slayertower_sc_chaintop"),
                sideA = tile(3421, 3550, 0),
                sideB = tile(3421, 3550, 1),
                move = Climb(AgilityAnims.CLIMB_LADDER),
            ),
            AgilityShortcut(
                name = "Narrow crevice",
                level = 61,
                xp = 0.0,
                locs = listOf("loc.slayer_dungeon_2_sc_wall_crack"),
                sideA = tile(2730, 10008),
                sideB = tile(2735, 10008),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Rocks",
                level = 62,
                xp = 0.0,
                locs = listOf("loc.mount_karuulm_shortcut_rocks"),
                sideA = tile(1324, 3787),
                sideB = tile(1324, 3795),
                move = Climb(),
            ),
            AgilityShortcut(
                name = "Loose railing",
                level = 63,
                xp = 0.0,
                locs = listOf("loc.deepdungeonlooserailing"),
                sideA = tile(2935, 9810),
                sideB = tile(2936, 9810),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Rocks",
                level = 68,
                xp = 0.0,
                locs = listOf("loc.ice_mountain_shortcut_top", "loc.ice_mountain_shortcut_bottom"),
                sideA = tile(2997, 3483),
                sideB = tile(3002, 3483),
                move = Climb(),
            ),
            AgilityShortcut(
                name = "Obstacle pipe",
                level = 70,
                xp = 10.0,
                locs = listOf("loc.taverly_dungeon_pipe_sc"),
                sideA = tile(2886, 9799),
                sideB = tile(2892, 9799),
                move = pipe,
            ),
            AgilityShortcut(
                name = "Spikey chain",
                level = 71,
                xp = 0.0,
                locs = listOf("loc.slayertower_sc_chainbottom", "loc.slayertower_sc_chaintop"),
                sideA = tile(3446, 3576, 1),
                sideB = tile(3446, 3576, 2),
                move = Climb(AgilityAnims.CLIMB_LADDER),
            ),
            AgilityShortcut(
                name = "Tunnel",
                level = 72,
                xp = 0.0,
                locs = listOf("loc.slayer_cave_tunnel_right", "loc.slayer_cave_tunnel_left"),
                sideA = tile(2429, 9806),
                sideB = tile(2435, 9806),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Tunnel",
                level = 72,
                xp = 0.0,
                locs = listOf("loc.cavewall_shortcut_wyvern_north", "loc.cavewall_shortcut_wyvern_south"),
                sideA = tile(3025, 9571),
                sideB = tile(3034, 9558),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Dry stone wall",
                level = 72,
                xp = 25.0,
                locs = listOf("loc.barrows_drystonewall_shortcut"),
                sideA = tile(3545, 3282),
                sideB = tile(3546, 3282),
                move = Jump(),
            ),
            AgilityShortcut(
                name = "Crevice",
                level = 77,
                xp = 10.0,
                locs = listOf("loc.wilderness_slayer_cave_crevice"),
                sideA = tile(3334, 10118),
                sideB = tile(3334, 10122),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Crevice",
                level = 77,
                xp = 10.0,
                locs = listOf("loc.wilderness_slayer_cave_crevice"),
                sideA = tile(3342, 10148),
                sideB = tile(3342, 10154),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Crevice",
                level = 77,
                xp = 10.0,
                locs = listOf("loc.wilderness_slayer_cave_crevice"),
                sideA = tile(3434, 10090),
                sideB = tile(3434, 10094),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Crevice",
                level = 77,
                xp = 10.0,
                locs = listOf("loc.wilderness_slayer_cave_crevice"),
                sideA = tile(3435, 10111),
                sideB = tile(3435, 10116),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Tight gap",
                level = 78,
                xp = 1.0,
                locs = listOf("loc.prif_slayer_dungeon_shortcut_1a", "loc.prif_slayer_dungeon_shortcut_1b"),
                sideA = tile(3222, 12441),
                sideB = tile(3216, 12441),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Strange floor",
                level = 80,
                xp = 12.5,
                locs = listOf("loc.taverly_dungeon_floor_spikes_sc"),
                sideA = tile(2878, 9813),
                sideB = tile(2880, 9813),
                move = Jump(AgilityAnims.JUMP),
            ),
            AgilityShortcut(
                name = "Tunnel",
                level = 82,
                xp = 0.0,
                locs = listOf("loc.cavewall_shortcut_wyvern_west", "loc.cavewall_shortcut_wyvern_east"),
                sideA = tile(3013, 9549),
                sideB = tile(3024, 9553),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Tight gap",
                level = 84,
                xp = 1.5,
                locs = listOf("loc.prif_slayer_dungeon_shortcut_2a", "loc.prif_slayer_dungeon_shortcut_2b"),
                sideA = tile(3242, 12420),
                sideB = tile(3232, 12420),
                move = crawl,
            ),
            AgilityShortcut(
                name = "Rocks",
                level = 84,
                xp = 0.0,
                locs = listOf("loc.crandor_shortcut_top", "loc.crandor_shortcut_bottom"),
                sideA = tile(2832, 3252),
                sideB = tile(2832, 3247),
                move = Climb(),
            ),
            AgilityShortcut(
                name = "Rocks",
                level = 85,
                xp = 0.0,
                locs =
                    listOf(
                        "loc.dagannoth_waterbirth_rock_climb_agility_shortcut_bottom",
                        "loc.dagannoth_waterbirth_rock_climb_agility_shortcut_top",
                    ),
                sideA = tile(2547, 3749),
                sideB = tile(2547, 3744),
                move = Climb(),
            ),
            AgilityShortcut(
                name = "Mysterious pipe",
                level = 88,
                xp = 0.0,
                locs = listOf("loc.karuulm_dungeon_shortcut_pipe_active"),
                sideA = tile(1316, 10213),
                sideB = tile(1346, 10232),
                move = pipe,
            ),
            AgilityShortcut(
                name = "Crevice",
                level = 96,
                xp = 7.5,
                locs = listOf("loc.legends_quest_cave_shortcut"),
                sideA = tile(2764, 9339),
                sideB = tile(2770, 9340),
                move = crawl,
            ),
        )
}
